namespace PLFinal.View
{
    partial class Peminjaman
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Peminjaman));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.txtNama = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnCari = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lvwPeminjaman = new System.Windows.Forms.ListView();
            this.btnTambah = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHapus = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRefresh = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnSelesai = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.label1 = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // txtNama
            // 
            this.txtNama.AcceptsReturn = false;
            this.txtNama.AcceptsTab = false;
            this.txtNama.AnimationSpeed = 200;
            this.txtNama.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtNama.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtNama.BackColor = System.Drawing.Color.Transparent;
            this.txtNama.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtNama.BackgroundImage")));
            this.txtNama.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtNama.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtNama.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtNama.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtNama.BorderRadius = 1;
            this.txtNama.BorderThickness = 1;
            this.txtNama.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtNama.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNama.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtNama.DefaultText = "";
            this.txtNama.FillColor = System.Drawing.Color.White;
            this.txtNama.HideSelection = true;
            this.txtNama.IconLeft = null;
            this.txtNama.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNama.IconPadding = 10;
            this.txtNama.IconRight = null;
            this.txtNama.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtNama.Lines = new string[0];
            this.txtNama.Location = new System.Drawing.Point(411, 338);
            this.txtNama.MaxLength = 32767;
            this.txtNama.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtNama.Modified = false;
            this.txtNama.Multiline = false;
            this.txtNama.Name = "txtNama";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNama.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtNama.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNama.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtNama.OnIdleState = stateProperties4;
            this.txtNama.Padding = new System.Windows.Forms.Padding(3);
            this.txtNama.PasswordChar = '\0';
            this.txtNama.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtNama.PlaceholderText = "Enter text";
            this.txtNama.ReadOnly = false;
            this.txtNama.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtNama.SelectedText = "";
            this.txtNama.SelectionLength = 0;
            this.txtNama.SelectionStart = 0;
            this.txtNama.ShortcutsEnabled = true;
            this.txtNama.Size = new System.Drawing.Size(698, 53);
            this.txtNama.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtNama.TabIndex = 1;
            this.txtNama.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtNama.TextMarginBottom = 0;
            this.txtNama.TextMarginLeft = 3;
            this.txtNama.TextMarginTop = 0;
            this.txtNama.TextPlaceholder = "Enter text";
            this.txtNama.UseSystemPasswordChar = false;
            this.txtNama.WordWrap = true;
            // 
            // btnCari
            // 
            this.btnCari.AllowAnimations = true;
            this.btnCari.AllowMouseEffects = true;
            this.btnCari.AllowToggling = false;
            this.btnCari.AnimationSpeed = 200;
            this.btnCari.AutoGenerateColors = false;
            this.btnCari.AutoRoundBorders = false;
            this.btnCari.AutoSizeLeftIcon = true;
            this.btnCari.AutoSizeRightIcon = true;
            this.btnCari.BackColor = System.Drawing.Color.Transparent;
            this.btnCari.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnCari.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCari.BackgroundImage")));
            this.btnCari.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCari.ButtonText = "Cari";
            this.btnCari.ButtonTextMarginLeft = 0;
            this.btnCari.ColorContrastOnClick = 45;
            this.btnCari.ColorContrastOnHover = 45;
            this.btnCari.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnCari.CustomizableEdges = borderEdges1;
            this.btnCari.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCari.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCari.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCari.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCari.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCari.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnCari.ForeColor = System.Drawing.Color.White;
            this.btnCari.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCari.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCari.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCari.IconMarginLeft = 11;
            this.btnCari.IconPadding = 10;
            this.btnCari.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCari.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCari.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCari.IconSize = 25;
            this.btnCari.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCari.IdleBorderRadius = 1;
            this.btnCari.IdleBorderThickness = 1;
            this.btnCari.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnCari.IdleIconLeftImage = null;
            this.btnCari.IdleIconRightImage = null;
            this.btnCari.IndicateFocus = false;
            this.btnCari.Location = new System.Drawing.Point(1140, 341);
            this.btnCari.Name = "btnCari";
            this.btnCari.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCari.OnDisabledState.BorderRadius = 1;
            this.btnCari.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCari.OnDisabledState.BorderThickness = 1;
            this.btnCari.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCari.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCari.OnDisabledState.IconLeftImage = null;
            this.btnCari.OnDisabledState.IconRightImage = null;
            this.btnCari.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCari.onHoverState.BorderRadius = 1;
            this.btnCari.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCari.onHoverState.BorderThickness = 1;
            this.btnCari.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCari.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCari.onHoverState.IconLeftImage = null;
            this.btnCari.onHoverState.IconRightImage = null;
            this.btnCari.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnCari.OnIdleState.BorderRadius = 1;
            this.btnCari.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCari.OnIdleState.BorderThickness = 1;
            this.btnCari.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCari.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnCari.OnIdleState.IconLeftImage = null;
            this.btnCari.OnIdleState.IconRightImage = null;
            this.btnCari.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCari.OnPressedState.BorderRadius = 1;
            this.btnCari.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCari.OnPressedState.BorderThickness = 1;
            this.btnCari.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCari.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCari.OnPressedState.IconLeftImage = null;
            this.btnCari.OnPressedState.IconRightImage = null;
            this.btnCari.Size = new System.Drawing.Size(150, 50);
            this.btnCari.TabIndex = 2;
            this.btnCari.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCari.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCari.TextMarginLeft = 0;
            this.btnCari.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCari.UseDefaultRadiusAndThickness = true;
            this.btnCari.Click += new System.EventHandler(this.btnCari_Click);
            // 
            // lvwPeminjaman
            // 
            this.lvwPeminjaman.HideSelection = false;
            this.lvwPeminjaman.Location = new System.Drawing.Point(133, 457);
            this.lvwPeminjaman.Name = "lvwPeminjaman";
            this.lvwPeminjaman.Size = new System.Drawing.Size(1157, 574);
            this.lvwPeminjaman.TabIndex = 3;
            this.lvwPeminjaman.UseCompatibleStateImageBehavior = false;
            this.lvwPeminjaman.SelectedIndexChanged += new System.EventHandler(this.lvwPeminjaman_SelectedIndexChanged);
            // 
            // btnTambah
            // 
            this.btnTambah.AllowAnimations = true;
            this.btnTambah.AllowMouseEffects = true;
            this.btnTambah.AllowToggling = false;
            this.btnTambah.AnimationSpeed = 200;
            this.btnTambah.AutoGenerateColors = false;
            this.btnTambah.AutoRoundBorders = false;
            this.btnTambah.AutoSizeLeftIcon = true;
            this.btnTambah.AutoSizeRightIcon = true;
            this.btnTambah.BackColor = System.Drawing.Color.Transparent;
            this.btnTambah.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnTambah.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnTambah.BackgroundImage")));
            this.btnTambah.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTambah.ButtonText = "Tambah";
            this.btnTambah.ButtonTextMarginLeft = 0;
            this.btnTambah.ColorContrastOnClick = 45;
            this.btnTambah.ColorContrastOnHover = 45;
            this.btnTambah.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnTambah.CustomizableEdges = borderEdges2;
            this.btnTambah.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnTambah.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTambah.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTambah.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTambah.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnTambah.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnTambah.ForeColor = System.Drawing.Color.White;
            this.btnTambah.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnTambah.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnTambah.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnTambah.IconMarginLeft = 11;
            this.btnTambah.IconPadding = 10;
            this.btnTambah.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnTambah.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnTambah.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnTambah.IconSize = 25;
            this.btnTambah.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnTambah.IdleBorderRadius = 1;
            this.btnTambah.IdleBorderThickness = 1;
            this.btnTambah.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnTambah.IdleIconLeftImage = null;
            this.btnTambah.IdleIconRightImage = null;
            this.btnTambah.IndicateFocus = false;
            this.btnTambah.Location = new System.Drawing.Point(133, 1072);
            this.btnTambah.Name = "btnTambah";
            this.btnTambah.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnTambah.OnDisabledState.BorderRadius = 1;
            this.btnTambah.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTambah.OnDisabledState.BorderThickness = 1;
            this.btnTambah.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnTambah.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnTambah.OnDisabledState.IconLeftImage = null;
            this.btnTambah.OnDisabledState.IconRightImage = null;
            this.btnTambah.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTambah.onHoverState.BorderRadius = 1;
            this.btnTambah.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTambah.onHoverState.BorderThickness = 1;
            this.btnTambah.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnTambah.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnTambah.onHoverState.IconLeftImage = null;
            this.btnTambah.onHoverState.IconRightImage = null;
            this.btnTambah.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnTambah.OnIdleState.BorderRadius = 1;
            this.btnTambah.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTambah.OnIdleState.BorderThickness = 1;
            this.btnTambah.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnTambah.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnTambah.OnIdleState.IconLeftImage = null;
            this.btnTambah.OnIdleState.IconRightImage = null;
            this.btnTambah.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTambah.OnPressedState.BorderRadius = 1;
            this.btnTambah.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnTambah.OnPressedState.BorderThickness = 1;
            this.btnTambah.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnTambah.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnTambah.OnPressedState.IconLeftImage = null;
            this.btnTambah.OnPressedState.IconRightImage = null;
            this.btnTambah.Size = new System.Drawing.Size(150, 67);
            this.btnTambah.TabIndex = 4;
            this.btnTambah.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnTambah.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnTambah.TextMarginLeft = 0;
            this.btnTambah.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnTambah.UseDefaultRadiusAndThickness = true;
            this.btnTambah.Click += new System.EventHandler(this.btnTambah_Click);
            // 
            // btnEdit
            // 
            this.btnEdit.AllowAnimations = true;
            this.btnEdit.AllowMouseEffects = true;
            this.btnEdit.AllowToggling = false;
            this.btnEdit.AnimationSpeed = 200;
            this.btnEdit.AutoGenerateColors = false;
            this.btnEdit.AutoRoundBorders = false;
            this.btnEdit.AutoSizeLeftIcon = true;
            this.btnEdit.AutoSizeRightIcon = true;
            this.btnEdit.BackColor = System.Drawing.Color.Transparent;
            this.btnEdit.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEdit.BackgroundImage")));
            this.btnEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.ButtonText = "Edit";
            this.btnEdit.ButtonTextMarginLeft = 0;
            this.btnEdit.ColorContrastOnClick = 45;
            this.btnEdit.ColorContrastOnHover = 45;
            this.btnEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnEdit.CustomizableEdges = borderEdges3;
            this.btnEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEdit.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEdit.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnEdit.ForeColor = System.Drawing.Color.White;
            this.btnEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEdit.IconMarginLeft = 11;
            this.btnEdit.IconPadding = 10;
            this.btnEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEdit.IconSize = 25;
            this.btnEdit.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.IdleBorderRadius = 1;
            this.btnEdit.IdleBorderThickness = 1;
            this.btnEdit.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.IdleIconLeftImage = null;
            this.btnEdit.IdleIconRightImage = null;
            this.btnEdit.IndicateFocus = false;
            this.btnEdit.Location = new System.Drawing.Point(308, 1072);
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.OnDisabledState.BorderRadius = 1;
            this.btnEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnDisabledState.BorderThickness = 1;
            this.btnEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEdit.OnDisabledState.IconLeftImage = null;
            this.btnEdit.OnDisabledState.IconRightImage = null;
            this.btnEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEdit.onHoverState.BorderRadius = 1;
            this.btnEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.onHoverState.BorderThickness = 1;
            this.btnEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.onHoverState.IconLeftImage = null;
            this.btnEdit.onHoverState.IconRightImage = null;
            this.btnEdit.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.OnIdleState.BorderRadius = 1;
            this.btnEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnIdleState.BorderThickness = 1;
            this.btnEdit.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnEdit.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.OnIdleState.IconLeftImage = null;
            this.btnEdit.OnIdleState.IconRightImage = null;
            this.btnEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEdit.OnPressedState.BorderRadius = 1;
            this.btnEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnPressedState.BorderThickness = 1;
            this.btnEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.OnPressedState.IconLeftImage = null;
            this.btnEdit.OnPressedState.IconRightImage = null;
            this.btnEdit.Size = new System.Drawing.Size(150, 67);
            this.btnEdit.TabIndex = 5;
            this.btnEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEdit.TextMarginLeft = 0;
            this.btnEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEdit.UseDefaultRadiusAndThickness = true;
            this.btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            // 
            // btnHapus
            // 
            this.btnHapus.AllowAnimations = true;
            this.btnHapus.AllowMouseEffects = true;
            this.btnHapus.AllowToggling = false;
            this.btnHapus.AnimationSpeed = 200;
            this.btnHapus.AutoGenerateColors = false;
            this.btnHapus.AutoRoundBorders = false;
            this.btnHapus.AutoSizeLeftIcon = true;
            this.btnHapus.AutoSizeRightIcon = true;
            this.btnHapus.BackColor = System.Drawing.Color.Transparent;
            this.btnHapus.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnHapus.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHapus.BackgroundImage")));
            this.btnHapus.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.ButtonText = "Hapus";
            this.btnHapus.ButtonTextMarginLeft = 0;
            this.btnHapus.ColorContrastOnClick = 45;
            this.btnHapus.ColorContrastOnHover = 45;
            this.btnHapus.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnHapus.CustomizableEdges = borderEdges4;
            this.btnHapus.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHapus.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHapus.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHapus.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHapus.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHapus.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnHapus.ForeColor = System.Drawing.Color.White;
            this.btnHapus.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHapus.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHapus.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHapus.IconMarginLeft = 11;
            this.btnHapus.IconPadding = 10;
            this.btnHapus.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHapus.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHapus.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHapus.IconSize = 25;
            this.btnHapus.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnHapus.IdleBorderRadius = 1;
            this.btnHapus.IdleBorderThickness = 1;
            this.btnHapus.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnHapus.IdleIconLeftImage = null;
            this.btnHapus.IdleIconRightImage = null;
            this.btnHapus.IndicateFocus = false;
            this.btnHapus.Location = new System.Drawing.Point(487, 1072);
            this.btnHapus.Name = "btnHapus";
            this.btnHapus.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHapus.OnDisabledState.BorderRadius = 1;
            this.btnHapus.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.OnDisabledState.BorderThickness = 1;
            this.btnHapus.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHapus.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHapus.OnDisabledState.IconLeftImage = null;
            this.btnHapus.OnDisabledState.IconRightImage = null;
            this.btnHapus.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnHapus.onHoverState.BorderRadius = 1;
            this.btnHapus.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.onHoverState.BorderThickness = 1;
            this.btnHapus.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnHapus.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHapus.onHoverState.IconLeftImage = null;
            this.btnHapus.onHoverState.IconRightImage = null;
            this.btnHapus.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnHapus.OnIdleState.BorderRadius = 1;
            this.btnHapus.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.OnIdleState.BorderThickness = 1;
            this.btnHapus.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnHapus.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnHapus.OnIdleState.IconLeftImage = null;
            this.btnHapus.OnIdleState.IconRightImage = null;
            this.btnHapus.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHapus.OnPressedState.BorderRadius = 1;
            this.btnHapus.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHapus.OnPressedState.BorderThickness = 1;
            this.btnHapus.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHapus.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHapus.OnPressedState.IconLeftImage = null;
            this.btnHapus.OnPressedState.IconRightImage = null;
            this.btnHapus.Size = new System.Drawing.Size(150, 67);
            this.btnHapus.TabIndex = 6;
            this.btnHapus.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHapus.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHapus.TextMarginLeft = 0;
            this.btnHapus.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHapus.UseDefaultRadiusAndThickness = true;
            this.btnHapus.Click += new System.EventHandler(this.btnHapus_Click);
            // 
            // btnRefresh
            // 
            this.btnRefresh.AllowAnimations = true;
            this.btnRefresh.AllowMouseEffects = true;
            this.btnRefresh.AllowToggling = false;
            this.btnRefresh.AnimationSpeed = 200;
            this.btnRefresh.AutoGenerateColors = false;
            this.btnRefresh.AutoRoundBorders = false;
            this.btnRefresh.AutoSizeLeftIcon = true;
            this.btnRefresh.AutoSizeRightIcon = true;
            this.btnRefresh.BackColor = System.Drawing.Color.Transparent;
            this.btnRefresh.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnRefresh.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRefresh.BackgroundImage")));
            this.btnRefresh.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.ButtonText = "Refresh";
            this.btnRefresh.ButtonTextMarginLeft = 0;
            this.btnRefresh.ColorContrastOnClick = 45;
            this.btnRefresh.ColorContrastOnHover = 45;
            this.btnRefresh.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnRefresh.CustomizableEdges = borderEdges5;
            this.btnRefresh.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRefresh.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRefresh.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRefresh.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRefresh.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRefresh.IconMarginLeft = 11;
            this.btnRefresh.IconPadding = 10;
            this.btnRefresh.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRefresh.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRefresh.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRefresh.IconSize = 25;
            this.btnRefresh.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRefresh.IdleBorderRadius = 1;
            this.btnRefresh.IdleBorderThickness = 1;
            this.btnRefresh.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnRefresh.IdleIconLeftImage = null;
            this.btnRefresh.IdleIconRightImage = null;
            this.btnRefresh.IndicateFocus = false;
            this.btnRefresh.Location = new System.Drawing.Point(668, 1072);
            this.btnRefresh.Name = "btnRefresh";
            this.btnRefresh.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRefresh.OnDisabledState.BorderRadius = 1;
            this.btnRefresh.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnDisabledState.BorderThickness = 1;
            this.btnRefresh.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRefresh.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRefresh.OnDisabledState.IconLeftImage = null;
            this.btnRefresh.OnDisabledState.IconRightImage = null;
            this.btnRefresh.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRefresh.onHoverState.BorderRadius = 1;
            this.btnRefresh.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.onHoverState.BorderThickness = 1;
            this.btnRefresh.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRefresh.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.onHoverState.IconLeftImage = null;
            this.btnRefresh.onHoverState.IconRightImage = null;
            this.btnRefresh.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRefresh.OnIdleState.BorderRadius = 1;
            this.btnRefresh.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnIdleState.BorderThickness = 1;
            this.btnRefresh.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnRefresh.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnIdleState.IconLeftImage = null;
            this.btnRefresh.OnIdleState.IconRightImage = null;
            this.btnRefresh.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRefresh.OnPressedState.BorderRadius = 1;
            this.btnRefresh.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRefresh.OnPressedState.BorderThickness = 1;
            this.btnRefresh.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRefresh.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRefresh.OnPressedState.IconLeftImage = null;
            this.btnRefresh.OnPressedState.IconRightImage = null;
            this.btnRefresh.Size = new System.Drawing.Size(150, 67);
            this.btnRefresh.TabIndex = 7;
            this.btnRefresh.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRefresh.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRefresh.TextMarginLeft = 0;
            this.btnRefresh.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRefresh.UseDefaultRadiusAndThickness = true;
            // 
            // btnSelesai
            // 
            this.btnSelesai.AllowAnimations = true;
            this.btnSelesai.AllowMouseEffects = true;
            this.btnSelesai.AllowToggling = false;
            this.btnSelesai.AnimationSpeed = 200;
            this.btnSelesai.AutoGenerateColors = false;
            this.btnSelesai.AutoRoundBorders = false;
            this.btnSelesai.AutoSizeLeftIcon = true;
            this.btnSelesai.AutoSizeRightIcon = true;
            this.btnSelesai.BackColor = System.Drawing.Color.Transparent;
            this.btnSelesai.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnSelesai.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSelesai.BackgroundImage")));
            this.btnSelesai.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelesai.ButtonText = "Selesai";
            this.btnSelesai.ButtonTextMarginLeft = 0;
            this.btnSelesai.ColorContrastOnClick = 45;
            this.btnSelesai.ColorContrastOnHover = 45;
            this.btnSelesai.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnSelesai.CustomizableEdges = borderEdges6;
            this.btnSelesai.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSelesai.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSelesai.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSelesai.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSelesai.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSelesai.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnSelesai.ForeColor = System.Drawing.Color.White;
            this.btnSelesai.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSelesai.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSelesai.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSelesai.IconMarginLeft = 11;
            this.btnSelesai.IconPadding = 10;
            this.btnSelesai.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSelesai.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSelesai.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSelesai.IconSize = 25;
            this.btnSelesai.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSelesai.IdleBorderRadius = 1;
            this.btnSelesai.IdleBorderThickness = 1;
            this.btnSelesai.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnSelesai.IdleIconLeftImage = null;
            this.btnSelesai.IdleIconRightImage = null;
            this.btnSelesai.IndicateFocus = false;
            this.btnSelesai.Location = new System.Drawing.Point(1140, 1072);
            this.btnSelesai.Name = "btnSelesai";
            this.btnSelesai.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSelesai.OnDisabledState.BorderRadius = 1;
            this.btnSelesai.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelesai.OnDisabledState.BorderThickness = 1;
            this.btnSelesai.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSelesai.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSelesai.OnDisabledState.IconLeftImage = null;
            this.btnSelesai.OnDisabledState.IconRightImage = null;
            this.btnSelesai.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSelesai.onHoverState.BorderRadius = 1;
            this.btnSelesai.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelesai.onHoverState.BorderThickness = 1;
            this.btnSelesai.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSelesai.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSelesai.onHoverState.IconLeftImage = null;
            this.btnSelesai.onHoverState.IconRightImage = null;
            this.btnSelesai.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnSelesai.OnIdleState.BorderRadius = 1;
            this.btnSelesai.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelesai.OnIdleState.BorderThickness = 1;
            this.btnSelesai.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnSelesai.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSelesai.OnIdleState.IconLeftImage = null;
            this.btnSelesai.OnIdleState.IconRightImage = null;
            this.btnSelesai.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSelesai.OnPressedState.BorderRadius = 1;
            this.btnSelesai.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSelesai.OnPressedState.BorderThickness = 1;
            this.btnSelesai.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSelesai.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSelesai.OnPressedState.IconLeftImage = null;
            this.btnSelesai.OnPressedState.IconRightImage = null;
            this.btnSelesai.Size = new System.Drawing.Size(150, 67);
            this.btnSelesai.TabIndex = 8;
            this.btnSelesai.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSelesai.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSelesai.TextMarginLeft = 0;
            this.btnSelesai.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSelesai.UseDefaultRadiusAndThickness = true;
            this.btnSelesai.Click += new System.EventHandler(this.btnSelesai_Click);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox1.Image")));
            this.pictureBox1.Location = new System.Drawing.Point(94, 44);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(350, 275);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox1.TabIndex = 9;
            this.pictureBox1.TabStop = false;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.875F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.Highlight;
            this.label1.Location = new System.Drawing.Point(128, 354);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(261, 25);
            this.label1.TabIndex = 10;
            this.label1.Text = "CARI NAMA PEMINJAM";
            // 
            // Peminjaman
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(12F, 25F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1408, 1259);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pictureBox1);
            this.Controls.Add(this.btnSelesai);
            this.Controls.Add(this.btnRefresh);
            this.Controls.Add(this.btnHapus);
            this.Controls.Add(this.btnEdit);
            this.Controls.Add(this.btnTambah);
            this.Controls.Add(this.lvwPeminjaman);
            this.Controls.Add(this.btnCari);
            this.Controls.Add(this.txtNama);
            this.Name = "Peminjaman";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Riwayat Peminjaman";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox txtNama;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCari;
        private System.Windows.Forms.ListView lvwPeminjaman;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnTambah;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEdit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHapus;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRefresh;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSelesai;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.Label label1;
    }
}